[datasets]
rice = "/home/shisk/data/rice/h5ad/h5ad_sunfy/ano_v1_kit_2048_state_ready_obsprocessed.h5ad"

[training]
rice = "train"

[fewshot."rice.kitaake"]
val = [ 
    "LOC_Os02g04430", "LOC_Os07g35690", "LOC_Os05g41370", 
    "LOC_Os07g36780", "LOC_Os01g12420"
]
test = [ 
    "LOC_Os07g35370", "LOC_Os07g35790", "LOC_Os01g48040", 
    "LOC_Os04g53994", "LOC_Os05g03450"
]
